events {}

http {
    upstream home_app {
        server home_app:3000;   # container_name:port
    }

    upstream cart_app {
        server cart_app:3000;   # container_name:port
    }

    server {
        listen 80;

        # Cart rotası
        location /cart/ {
            proxy_pass http://cart_app;   
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Home rotası
        location / {
            proxy_pass http://home_app/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
